### ISSUE TITLE
Please take manifest's devDependencies into account.

### ISSUE THREAD

**Issue by danengholm** [heikkipora/registry-sync#12]
My package.json has a devDependencies section in addition (and a sibling) to dependencies. I'd like registry-sync to also download any packages enumerated in this section.

**Comment by heikkipora** [comment]
I always use a separate (non-application-specific) package.json where all modules are listed under "dependencies" so I didn't think that some people might also use an actual application-specific package.json :)  Sounds like a valid feature to me.

I will do it at some point during the coming weeks. If you want it quicker, I'm more than happy to accept a pull request.

**Comment by heikkipora** [comment]
Actually.. It was so straightforward to implement that I did it already :)  Released as v1.4.4 (https://github.com/heikkipora/registry-sync/releases/tag/1.4.4) to npm

**Comment by danengholm** [comment]
Thanks!
