### ISSUE TITLE
Already downloaded modules lose their integrity field on subsequent runs

### ISSUE THREAD

**Issue by joux3** [heikkipora/registry-sync#13]
Repro:
1. Add `pg-pool` as dependency (this at least currently lacks a `integrity` field in npmjs.org registry)
2. Run `registry-sync` and observe that an `integrity` field is generated under `pg-pool/index.json`
3. Rerun `registry-sync` and see that the `integrity` field is missing

**Comment by heikkipora** [comment]
Fixed by https://github.com/heikkipora/registry-sync/commit/670fefb604465e56d9449a0076de118e897f8dcc
