### ISSUE TITLE
feature request: recursive mirror

### ISSUE THREAD

**Issue by DanielRuf** [heikkipora/registry-sync#17]
It might be good to have an option to do a recursive scan for lockfiles eg for monorepos, submodules, peer dependencies and so on.

**Comment by heikkipora** [comment]
This is a bit too far from the main registry-sync "use case" which is:
 - have a single source of truth (i.e. a lock file) for what gets mirrored
 - have the projects that actually depend on those mirrored packages somewhere else
 - don't have/need access to those projects where registry-sync is executed
