### ISSUE TITLE
feature request: support yarn.lock and shrinkwrap.yml

### ISSUE THREAD

**Issue by DanielRuf** [heikkipora/registry-sync#18]
Adding support for yarn (yarn.lock) and pnpm (shrinkwrap.yml) might be useful.

**Comment by heikkipora** [comment]
True indeed. Want to do one or both of those and submit a pull request?

Anyway, I'll keep this issue open for a while to see if people need it and want to contribute.
I don't use yarn or pnpm myself so am not likely to do it myself :)

**Comment by DanielRuf** [comment]
cc @zkochan I guess you have a project with infos about the structure and might be some recommended principles.

**Comment by zkochan** [comment]
specs of `shrinkwrap.yaml`: https://github.com/pnpm/spec/blob/master/shrinkwrap/3.8.md

utils for reading/writing etc: https://github.com/pnpm/pnpm-shrinkwrap

**Comment by heikkipora** [comment]
Doesn't seem like a popular thing, closing.
