### ISSUE TITLE
feature request: mirror whole registry (with thresholds)

### ISSUE THREAD

**Issue by DanielRuf** [heikkipora/registry-sync#19]
I want to mirror the whole registry and set some thresholds (max bandwidth, max available storage, package syncs per day, intervals, ...).

Might be good to combine this or add this as plugin for verdaccio.

**Comment by heikkipora** [comment]
This is clearly out of the scope of registry-sync which is purpose-built for mirroring a defined set of packages with their dependencies. Mirroring the whole registry requires a completely different approach.
