### ISSUE TITLE
Adding new binary ABIs to use does not update existing packages

### ISSUE THREAD

**Issue by joux3** [heikkipora/registry-sync#20]
Repro:
1. run registry-sync for some packages with pre-built binaries for a single ABI
2. run it again, this time with multiple ABIs
3. see that binaries for the new ABIs are not downloaded

Only new packages get all the binaries for all the ABIs. Maybe store the last used ABIs in the cache file somehow and redownload all if the ABIs change?

**Comment by heikkipora** [comment]
Implemented and released: https://github.com/heikkipora/registry-sync/releases/tag/2.3.0
