### ISSUE TITLE
dev dependencies

### ISSUE THREAD

**Issue by timbell** [heikkipora/registry-sync#26]
Dev dependencies appear to be omitted by this:

https://github.com/heikkipora/registry-sync/blob/0750b49e15927a1ea2306f63f34f202d844be701/src/resolve.js#L62

Any chance of an option to allow dev dependencies to be included?

**Comment by heikkipora** [comment]
Sure, nobody just needed that before. I can do it at some point but the quickest way would be to submit a pull request for it.

**Comment by heikkipora** [comment]
```--incluDev``` option added in release https://github.com/heikkipora/registry-sync/releases/tag/2.4.5
